ORG	8000H

COLGREEN	EQU	0FFC5H
COLRED		EQU	0FFC6H
ROW		EQU	0FFC7H
SEGMENT		EQU	0FFC1H		;8BIT
SNAKECOL	EQU	30H
SNAKEROW	EQU	31H
FEEDCOL		EQU	32H
FEEDROW		EQU	33H
SCORE		EQU	34H

MOV	A,#00000000B
MOV	DPTR,#ROW
MOVX	@DPTR,A
MOV	DPTR,#COLGREEN
MOVX	@DPTR,A
MOV	DPTR,#COLRED
MOVX	@DPTR,A

MOV	SNAKECOL,#00010000B
MOV	SNAKEROW,#00010000B
MOV	FEEDCOL,#01000000B
MOV	FEEDROW,#00000100B
MOV	SCORE,#00H
CALL	BCD
MAIN:
	CALL	CHECKPLACE
	JMP	MAIN

LOOP:
	CALL	DISPSNAKE
	CALL	DELAY
	CALL	DISPFEED
	CALL	DELAY
	JMP	LOOP

SCOREADD:
	INC	SCORE
	MOV	A,SCORE
	CJNE	A,#64H,BCD
	MOV	SCORE,#00H
	JMP	BCD
	
CHECKPLACE:
	MOV	A,SNAKECOL
	CJNE	A,FEEDCOL,GOAHEAD
	MOV	A,SNAKEROW
	CJNE	A,FEEDROW,GOAHEAD
	CALL	SCOREADD	; GET FEED -> SCORE+1
	; NEW FEEDCOL,FEEDROW SET
GOAHEAD: RET


DISPSNAKE:
	MOV	DPTR,#ROW
	MOV	A,SNAKEROW
	MOVX	@DPTR,A

	MOV	DPTR,#COLGREEN
	MOV	A,SNAKECOL
	MOVX	@DPTR,A
	
	MOV	DPTR,#COLRED
	MOV	A,#00000000B
	MOVX	@DPTR,A
	RET
DISPFEED:
	MOV	DPTR,#ROW
	MOV	A,FEEDROW
	MOVX	@DPTR,A

	MOV	DPTR,#COLRED
	MOV	A,FEEDCOL
	MOVX	@DPTR,A

	MOV	DPTR,#COLGREEN
	MOV	A,#00000000B
	MOVX	@DPTR,A
	RET

BCD:	MOV	A,SCORE
	MOV	B,#10
	DIV	AB
	SWAP	A
	MOV	R0,B
	ORL	A,R0
	MOV	DPTR,#SEGMENT
	MOVX	@DPTR,A
	RET

DELAY:	MOV	R5,#0FFH
DELAY1:	MOV	R6,#0FFH
DELAY2:	DJNZ	R6,DELAY2
	DJNZ	R5,DELAY1
	RET